export interface Goal {
  id: string;
  title: string;
  description: string;
  status: 'not_started' | 'in_progress' | 'completed' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'critical';
  progress: number; // 0-100
  dueDate: string;
  createdAt: string;
  assignee: string;
  category: string;
}

export const goals: Goal[] = [
  {
    id: '1',
    title: 'השקת אתר חדש',
    description: 'עיצוב ופיתוח אתר החברה מחדש עם חוויית משתמש משופרת',
    status: 'in_progress',
    priority: 'high',
    progress: 65,
    dueDate: '2026-05-15',
    createdAt: '2026-01-10',
    assignee: 'נועה כהן',
    category: 'מוצר',
  },
  {
    id: '2',
    title: 'הגדלת בסיס לקוחות ב-30%',
    description: 'הרחבת בסיס הלקוחות באמצעות קמפיינים דיגיטליים ושותפויות',
    status: 'in_progress',
    priority: 'critical',
    progress: 42,
    dueDate: '2026-06-30',
    createdAt: '2026-01-01',
    assignee: 'יוסי לוי',
    category: 'שיווק',
  },
  {
    id: '3',
    title: 'הטמעת מערכת CRM',
    description: 'בחירה והטמעה של מערכת CRM לניהול קשרי לקוחות',
    status: 'completed',
    priority: 'high',
    progress: 100,
    dueDate: '2026-03-01',
    createdAt: '2025-11-15',
    assignee: 'מיכל אברהם',
    category: 'תפעול',
  },
  {
    id: '4',
    title: 'גיוס 5 מפתחים בכירים',
    description: 'חיזוק צוות הפיתוח עם מהנדסי תוכנה מנוסים',
    status: 'in_progress',
    priority: 'medium',
    progress: 40,
    dueDate: '2026-04-30',
    createdAt: '2026-01-20',
    assignee: 'דנה שמיר',
    category: 'משאבי אנוש',
  },
  {
    id: '5',
    title: 'הפחתת זמן תגובה ל-API',
    description: 'אופטימיזציה של שרתי ה-API להגיע לזמן תגובה מתחת ל-200ms',
    status: 'not_started',
    priority: 'medium',
    progress: 0,
    dueDate: '2026-07-15',
    createdAt: '2026-03-01',
    assignee: 'אלון דוד',
    category: 'טכנולוגיה',
  },
  {
    id: '6',
    title: 'השגת תקן ISO 27001',
    description: 'הכנת החברה לעמידה בתקן אבטחת מידע בינלאומי',
    status: 'in_progress',
    priority: 'high',
    progress: 25,
    dueDate: '2026-09-01',
    createdAt: '2026-02-01',
    assignee: 'רונית פרץ',
    category: 'אבטחה',
  },
  {
    id: '7',
    title: 'פיתוח אפליקציית מובייל',
    description: 'בניית אפליקציה ל-iOS ו-Android עם React Native',
    status: 'not_started',
    priority: 'high',
    progress: 0,
    dueDate: '2026-08-30',
    createdAt: '2026-03-15',
    assignee: 'עומר חדד',
    category: 'מוצר',
  },
  {
    id: '8',
    title: 'צמצום עלויות תשתית ב-20%',
    description: 'מעבר לארכיטקטורת serverless ואופטימיזציה של משאבי ענן',
    status: 'in_progress',
    priority: 'medium',
    progress: 55,
    dueDate: '2026-05-30',
    createdAt: '2026-01-15',
    assignee: 'אלון דוד',
    category: 'טכנולוגיה',
  },
  {
    id: '9',
    title: 'השקת תוכנית הכשרה פנימית',
    description: 'בניית מסלולי למידה והכשרה לעובדים חדשים וותיקים',
    status: 'completed',
    priority: 'low',
    progress: 100,
    dueDate: '2026-02-28',
    createdAt: '2025-12-01',
    assignee: 'דנה שמיר',
    category: 'משאבי אנוש',
  },
  {
    id: '10',
    title: 'שיפור ציון NPS ל-70+',
    description: 'שיפור שביעות רצון לקוחות דרך תמיכה משופרת ופיצ\'רים חדשים',
    status: 'in_progress',
    priority: 'critical',
    progress: 58,
    dueDate: '2026-06-30',
    createdAt: '2026-01-01',
    assignee: 'מיכל אברהם',
    category: 'שירות',
  },
  {
    id: '11',
    title: 'הקמת מערכת מוניטורינג',
    description: 'פריסת Grafana + Prometheus לניטור ביצועים בזמן אמת',
    status: 'completed',
    priority: 'high',
    progress: 100,
    dueDate: '2026-03-15',
    createdAt: '2026-01-05',
    assignee: 'עומר חדד',
    category: 'טכנולוגיה',
  },
  {
    id: '12',
    title: 'כניסה לשוק האירופי',
    description: 'התאמת המוצר ל-GDPR והשקה בגרמניה וצרפת',
    status: 'not_started',
    priority: 'critical',
    progress: 0,
    dueDate: '2026-10-01',
    createdAt: '2026-03-20',
    assignee: 'יוסי לוי',
    category: 'עסקי',
  },
];
